### ISSUE TITLE
StateMachine Logic Block

### ISSUE THREAD

**Issue by jabdoa2** [missionpinball/mpf#1051]
Implement a LogicBlock with a simple state machine.

```
state_machines:
  my_mode_state:
     start:
       transitions:
          - events: target_hit
             target_state: waiting_for_lock
     waiting_for_lock:
       post_on_state_start: start_timer, enable_lock
       post_on_state_stop: disable_lock
       transitions:
         - events: lock_full
           post: show_slides
           shows: multiball_qualified
           target_state: wait_for_mb_start
         - events: timer_timeouted
           post: disable_lock
           target_state: start
     wait_for_mb_start:
       transitions:
         - events: mb_ended
           target_state: start
```
