### ISSUE TITLE
Shot 'hit_events' not re-enabling

### ISSUE THREAD

**Issue by avanwinkle** [missionpinball/mpf#1052]
I've come across a bug in shots where those that use `hit_events` instead of `switch` don't properly re-enable after being disabled. I've scoured the code looking for where the `hit_events` behavior is defined, but could find nothing.

```
shots:
  switchy_shot:
    switch: s_orbit
    enable_events: enable_shots
    disable_events: disable_shots
  eventy_shot:
    hit_events: hit_that_shot
    enable_events: enable_shots
    disable_events: disable_shots
```
The result is this:
```
Event: ===== 's_orbit_active'
Event: ===== 'switchy_shot_hit'
Event: ===== 'hit_that_shot'
Event: ===== 'eventy_shot_hit'
Event: ===== 'disable_shots'
Event: ===== 's_orbit_active'
Event: ===== 'hit_that_shot'
Event: ===== 'enable_shots'
Event: ===== 'hit_that_shot'
Event: ===== 's_orbit_active'
Event: ===== 'switchy_shot_hit'
```
