### ISSUE TITLE
Prototype for Data Modelling

### ISSUE THREAD

**Issue by jabdoa2** [missionpinball/mpf#1053]
Implement the Prototype pattern for devices in config. They should be able to specify a prototype and overwrite all attributes. We probably need a way to mark devices as abtract/prototype to prevent instantiating them.

Further reading: http://gameprogrammingpatterns.com/prototype.html#prototypes-for-data-modeling

**Comment by jabdoa2** [comment]
Example with lights:
```
lights:
  playfield_insert: # WS2812
    _prototype: True
    type: grb
    tags: playfield
  playfield_gi: # WS2811
    _prototype: True
    type: rgb
    tags: playfield, gi
  l_my_insert1:
    number: 0-1
    prototype: playfield_insert
  l_my_gi1:
    number: 1-1
    prototype: playfield_gi
```
