### ISSUE TITLE
Add parameters for events created in shows.

### ISSUE THREAD

**Issue by MarkInc666** [missionpinball/mpf#1090]
example:
in code I can do this:
self.machine.events.post('set_flasher', dir=1, r=10,g=250,b=10)

in show?  something like this, or similar - is it possible?
```
# show_version=5
- time: 0
  events: 
    - event: set_flasher  
      dir: 1
      r: 250
      g: 250
      b: 0
```
