### ISSUE TITLE
Fixed duration on certain show steps

### ISSUE THREAD

**Issue by avanwinkle** [missionpinball/mpf#1102]
When adding LED "flashers" to my lighting shows over the weekend, I came up with some specific timings to replicate the flashing look of old-school flasher lights. When adding these flashers to shows, however, I was dismayed because any variation in the show speed would scale the flasher timing, either faster (so fast it didn't even flash) or slower (so slow it's just on, not "flashing").

I played with a few options to remedy this situation and was happiest with the addition of a show step setting `fixed_duration`. When True, this setting prevents a show's playback speed from scaling that particular step.

Here's an example of how that setting could be used: A show with a double-flash of an LED flasher and a long interval for looping. Currently, a designer would have to create a separate one of these shows for each interval period, or create a series of delay-callback combos to manually loop the show. With `fixed_duration`, a designer can use the show speed to scale the interval up and down while keeping the flash timing intact.

```
shows:
  flasher_show_double:
    - duration: 100ms
      fixed_duration: true
      lights:
        (flashers): off
    - duration: 100ms
      fixed_duration: true
      lights:
        (flashers): off
    - duration: 100ms
      fixed_duration: true
      lights:
        (flashers): on
    - duration: 10s
      lights:
        (flashers): off
```

I'd love some perspective on this issue from folks who've been around a while, especially anybody who helped transition away from `flashers:` and into the common `lights:` settings.

My working implementation of the feature is here: https://github.com/missionpinball/mpf/compare/dev...avanwinkle:show-step-fixed-duration

**Comment by jabdoa2** [comment]
I like the idea to have fixed length steps in shows. You could use flasher_player in your show (flashers section) to achieve constant length flashes. However, that show step would scale again. So yeah this makes sense.

We could even bring this to the next level by allowing templates for the duration of a step. The default would be:

duration_template: duration/speed

That would allow more dynamic stuff as well. What do you think?

**Comment by avanwinkle** [comment]
I like the idea, lots of possible uses for variable durations. I'm thinking of flashers that automatically get faster as a timer counts down, or shows that speed up every time a counter is hit. Neat! What do you suppose the overhead cost would be of recalculating the speed every iteration of the show, though? Too much?

In that case, the fixed duration would be `duration_template: duration` and use the standard dynamic value formula for the rest.

**Comment by jabdoa2** [comment]
Overhead should be fine since the usual delay will be larger than 1ms and our templates should a lot faster than that.

**Comment by avanwinkle** [comment]
I've implemented a draft of a `duration_function` setting: https://github.com/missionpinball/mpf/compare/dev...avanwinkle:show-step-fixed-duration

It feels kinda clunky, I think because I was hoping the config validator would auto-convert the setting values to Templates but it looks like show configs don't do that? 

Anyway, feedback and suggestions would be greatly appreciated!

**Comment by jabdoa2** [comment]
@avanwinkle i checked your branch. It look pretty clean and straightforward to me. I like it!

Some small remarks:
- I guess i would like to just re-purpose the "duration" setting instead of "duration_function". Duration is currently either int or float so they should work as placeholders (and we optimized native types in PlaceholderManager)
- The auto-conversion probably does not happen because we do not validate the individual show steps using config_validator (which would enfore types). I guess your way is fine.
- In your test you got a show where the step has a duration and the next step has a time:
```
  show_with_fixed_duration:
    - time: 0
    - time: '+2s'
    - time: '+2s'
      duration_function: duration
    - time: '+2s'
```
I guess that should not work because what will it use? +2s or the duration_function? Not sure if we error out on those cases currently (with the current duration) but if we don't we should.

Overall, I would be very happy to merge your changes to to MPF. So feel free to submit a PR.
