### ISSUE TITLE
Do we need device_collection_control_events?

### ISSUE THREAD

**Issue by jabdoa2** [missionpinball/mpf#1127]
Some untested device_collection_control_events exist in MPF:
```
    device_collection_control_events:
        autofires:
            - enable
            - disable
        ball_devices:
            - stop
            - eject_all
        coils:
            - disable
        flippers:
            - enable
            - disable
        lights:
            - "off"
        gi:
            - enable
            - disable
```
gi_enable will call enable on all devices in the gi collection. Do we need this or should this be removed? If we want to keep it we need a test and some documentation.
