### ISSUE TITLE
Timer control event change_tick_interval truncates float values to int.

### ISSUE THREAD

**Issue by kaydeeH** [missionpinball/mpf#1187]
Given the following config:

```
timers:
   meteorTimer:
     start_value: 30
     end_value: 0
     tick_interval: 1s
     direction: down
     start_running: yes
     control_events:
      - event: some_event
        action: change_tick_interval
        value: 0.1
```
When 'some_event' fires, the tick interval is set to 0 and the timer immediately runs out. I found that this is because the handler created for this is initialized with a zero. If I changed the value to 2, the handler was initialized to 2 and the tick_interval was doubled as expected.  I checked into the config_spec.py and found the issue:

```
timer_control_events:  # subconfig for mode timers
    __valid_in__: None
    action: single|enum(add,subtract,jump,start,stop,reset,restart,pause,set_tick_interval,change_tick_interval,\
reset_tick_interval)|
    event: single|str|
    value: single|int|None
```
The value is being validated as an int, which causes the value to be cast to int, loosing the decimals. When I changed this to 'num' the functionality worked as expected, so I believe that's all the fix requires. 

Also, the documentation for both the timer.py change_tick_interval method and the 'timers:' page in the online docs do not explain this functionality correctly. The're both wrong, but in different ways.
