### ISSUE TITLE
coil_player action 'off' crashes out

### ISSUE THREAD

**Issue by Snux** [missionpinball/mpf#1282]
Using 'off' as an action in a coil_player generates (at run time) an error that the action is not valid (**_Invalid action off_**).  Easily worked-around by using 'disabled' instead, but either the code needs fixing or the documentation updating.

So this works fine when the ball_cleared_ramp event comes in..

```
# Will activate a divertor depending on which lock is our target.  
coil_player:
   route_to_lock1:
      c_lowerDivertor:
         action: pulse
         pulse_ms: 3000
   route_to_lock2:
      c_upperDivertor:
         action: pulse
         pulse_ms: 3000
   ball_cleared_ramp: # Divertor did it's job, so can be switched off
      c_upperDivertor:
         action: disable
      c_lowerDivertor:
         action: disable
```

However with this config instead..

```
# Will activate a divertor depending on which lock is our target. 
coil_player:
   route_to_lock1:
      c_lowerDivertor:
         action: pulse
         pulse_ms: 3000
   route_to_lock2:
      c_upperDivertor:
         action: pulse
         pulse_ms: 3000
   ball_cleared_ramp: # Divertor did it's job, so can be switched off
      c_upperDivertor:
         action: off
      c_lowerDivertor:
         action: off
```

This is the error from the log..

Traceback (most recent call last):
  File "c:\users\mark\appdata\local\programs\python\python36\lib\site-packages\mpf\core\events.py", line 657, in _run_handlers
    result = handler.callback(**merged_kwargs)
  File "c:\users\mark\appdata\local\programs\python\python36\lib\site-packages\mpf\core\config_player.py", line 336, in config_play_callback
    **kwargs)
  File "c:\users\mark\appdata\local\programs\python\python36\lib\site-packages\mpf\config_players\coil_player.py", line 32, in play
    self.raise_config_error("Invalid action {}".format(action), 1, context=context)
  File "c:\users\mark\appdata\local\programs\python\python36\lib\site-packages\mpf\core\logging.py", line 139, in raise_config_error
    raise ConfigFileError(msg, error_no, self.log.name, context)
mpf.exceptions.ConfigFileError.ConfigFileError: Config File Error in coil_player: Invalid action off Error Code: CFE-coil_player-1 Context: lock_handler
