### ISSUE TITLE
System 11 A/C select relay handling

### ISSUE THREAD

**Issue by Snux** [missionpinball/mpf#1288]
[snux.zip](https://github.com/missionpinball/mpf/files/2730432/snux.zip)

Add 2 parameters to the snux: platform in config_spec.yaml... (the last 2 in this list)

```
snux:
    __valid_in__: machine
    flipper_enable_driver: single|machine(coils)|
    diag_led_driver: single|machine(coils)|
    platform: single|str|None
    console_log: single|enum(none,basic,full)|none
    file_log: single|enum(none,basic,full)|basic
    prefer_a_side_event: single|str|game_ended
    prefer_c_side_event: single|str|game_will_start
```

Modify the snux.py platform code to know what the A/C relay should do when at rest.  By default during game play it will now rest in the 'C' side (so relay is energised).  Typically flasher lamps are on the C side so they will get a quick response instead of having to wait for the relay to switch.  When the game is over the relay will prefer the 'A' side (so de-energised).  I've attached the snux.py code and the change to config_spec.yaml is mentioned above.  

I also need to update the docs to state that care should be taken if processing a lot of drives to the A and C sides at the same time.  That message applies regardless of this change.
