### ISSUE TITLE
Disallow more than one default in display definition

### ISSUE THREAD

**Issue by cfbenn** [missionpinball/mpf#1315]
When declaring multiple displays there is no check to make sure more than one is not set to default.

The code appears to take the last default display as the one to set.

Example:
(main_display is set as the default)
```

displays:
  default_display:
    width: 2560
    height: 720 
    default: true
  main_display:
    width: 1280
    height: 720
    default: true
  mini_display:
    width: 1280
    height: 720
    
```
