### ISSUE TITLE
Pass event args from show to slide_player

### ISSUE THREAD

**Issue by jabdoa2** [missionpinball/mpf#1367]
Make this example work (from https://groups.google.com/forum/#!topic/mpf-users/ln2y_qxGRg4) 

My match.yaml config has this show config in it:
```
show_player:
    no_match: 
        show_no_match:
            loops: 0
    has_match: 
        show_has_match:
            loops: 0
```

My show file is pretty simple and has this config:

```
#show_version=5
- time: 0
  slides: sld_match_generic_slide
- time: +4s
  slides: sld_match_slide
- time: +3s
```

My slide config is in a separate YAML file to my match.yaml and the area in question looks like this:

```
    sld_match_slide:
        widgets:
          - type: text
            style: match_result_success
            text: MATCH
            anchor_y: middle
            anchor_x: middle
            y: middle+40
            x: middle            
            animations:
              show_slide: pulse_bounce_half_sec
          - type: text
            text: (winner_number)
            style: match_result_success
            anchor_y: middle
            anchor_x: middle
            y: middle-40
            x: middle           
```
