### ISSUE TITLE
Support placeholders in keep_multiplier in bonus mode

### ISSUE THREAD

**Issue by jabdoa2** [missionpinball/mpf#1504]
Support placeholders in `keep_multiplier` (and maybe some more settings) in bonus mode:
```
##! mode: bonus

mode_settings:
    display_delay_ms: 500
    hurry_up_delay_ms: 500
    hurry_up_event: flipper_cancel
    # end_bonus_event: player_score
    #keep_multiplier: true #false            # automatically resets the bonus_multiplier var - this works
    keep_multiplier: true if {current_player.bonus_multiplier<=4} else false    # doesn't work
    #keep_multiplier: true if "{player_bonus_multiplier{value<5}" else false    # doesn't work
    bonus_entries:
        - event: eob_bonus
          score: 1000
          player_score_entry: bonus
          reset_player_score_entry: true
          skip_if_zero: true
```

See: https://groups.google.com/forum/#!topic/mpf-users/hWbm1qx3kKc
