### ISSUE TITLE
Multiball: Stacked traditional multiballs request too many balls for playfield on second multiball

### ISSUE THREAD

**Issue by rochuck** [missionpinball/mpf#1601]
I have two traditional 3-ball multiball locks devices. Both configured similarly, somewhat like:
```
multiball_locks:
 lock:
    balls_to_lock: 3
    balls_to_replace: 2
    lock_devices:  bd_lock

multiballs:
  mb:
    ball_count: 2
    ball_locks: bd_lock
    start_events: multiball_lock_lock_full
    replace_balls_in_play: true
    ball_count_type: add
```
In this scenario, when the first multiball is running (3 balls on the playfield) and the second multiball lock is completed (now 2 balls on the playfield and 3 in the second lock). The second multiball requests 5 balls, which is a problem. It should only request 3 from the ball lock device (for a total of 5 on the playfield). The issue I'm seeing is that there are now 5 balls in play (correct) but two queued ball requests for the playfield (messes up the game).

I believe the culprit may be this line:
https://github.com/missionpinball/mpf/blob/2c85d576e4f62c3ce46811aaa1d8c18175cc6f4c/mpf/devices/multiball.py#L80
since the `balls_to_replace` is high on additional multiballs. In my case if I just hard code this value to `1` it "works for me" &#8482;  Maybe this line should be `balls_to_replace= (from the multiball lock config) balls_to_lock-balls_to_replace`

If I'm missing the boat and just have a bad configuration please delete this issue.  On the other hand I'm willing to provide more details/clarity on what I'm seeing as well.
