### ISSUE TITLE
widget rectangle works draws area too small

### ISSUE THREAD

**Issue by Stefku** [missionpinball/mpf#1676]
I've got the config

```
displays:
  window:
    width: 1280
    height: 720
window:
  width: 1280
  height: 720
  title: Mission Pinball Framework
  resizable: false
  fullscreen: false
  borderless: false
  exit_on_escape: true
  source_display: window
```

With the following widget, there appears just an rectangle quarter of the window. Other widgets use the whole window.

```
    - type: rectangle
      x: 0
      y: 0
      width: 1280
      height: 720
      color: pink
```

<img width="1282" alt="Screenshot 2023-01-05 at 19 20 12" src="https://user-images.githubusercontent.com/2326881/210852599-31314b61-6562-4163-ac5d-5515a8b8590e.png">
