### ISSUE TITLE
variable player with conditional entries not working

### ISSUE THREAD

**Issue by worldpeace-germany** [missionpinball/mpf#1685]
Hello,

this is in reference to [this dicussion](https://github.com/orgs/missionpinball/discussions/83)

In summary if you have a variable player like this

```
variable_player:
  s_pop_bumper_1_active:
    score: 100
  s_target_red_1_active:
    score: 1000
    potato: 1
  s_target_red_1_active{current_player.status_target_light_red_0 == 0}: 
      status_target_light_red_0:
        int: 1       
        action: set     
  s_target_red_1_active{current_player.status_target_light_red_0 == 1}: 
      status_target_light_red_0:
        int: 0
        action: set 
```

you can see in the log 

```
EventManager: Event: ======'player_status_target_light_red_0'====== Args={'value': 1, 'prev_value': 0, 'change': 1, 'player_num': 1}
EventManager: Event: ======'player_status_target_light_red_0'====== Args={'value': 0, 'prev_value': 1, 'change': -1, 'player_num': 1}
```

that for each event  both variable player entries are being executed. If you swap the order in the config, the order in the log changes. Thus it shows that the last entry in the config wins. The system behaves as if the condition given in {} is completely ignored or always evaluated to true.

The Q&A discussion linked above shows

- for event player, the above is working fine, only variable player has that issue
- a fully virtual example is attached to the Q&A

If someone provides some "getting started" where I can find the relevant code I am will to try to debug and help.

**Comment by tp-ops** [comment]
I see this behavior in my game too.
I am using MPF v0.80 and thought it had to do with the new 'item_highlighted' event but that doesn't seem to be the case.

one less option

**Comment by avanwinkle** [comment]
I'm unable to reproduce this issue, so looking for some help.

@worldpeace-germany In your example, what's happening is that whichever event is processed first sets the `current_player.status_target_light_red_0` to the other value, and then the next event is processed and the value has been set to _that_ event's value, so that one is true as well. I.e. if the value is zero, the zero handler sets it to one, and then the one handlers sees that it's one, and sets it to zero.

The preferred approach here would be to use a shot for that switch and conditionally set the variable based on the shot state, or use a conditional event in the event_player to post the necessary event to set the variable. That way all of the switch callback handlers are done processing before the variable gets set.

@tp-ops Can you provide a sample of your code that's reproducing the issue?

Here's the snippet I added to base.yaml to test, and I see the correct (only one) variable being set.

```

event_player:
  mode_base_started:
    - test_event_with_condition_event|1s

variable_player:
  mode_base_started:
    test_eval:
      action: set
      int: 0
  test_event_with_condition_event{current_player.test_eval == 1}:
    condition_event_one:
      action: set
      string: "test_eval_is_1"
  test_event_with_condition_event{current_player.test_eval == 0}:
    condition_event_two:
      action: set
      string: "test_eval_is_0"
```
