### ISSUE TITLE
crashes after adding "score_reel_groups" to config

### ISSUE THREAD

**Issue by mrechte** [missionpinball/mpf#1721]
Hi.
After having added a configuration for score reels, as soon as the "base" mode starts (leaving attract mode), I get a crash:

```
Shutting down...
Event: ======'shutdown'====== Args={}
Event: ======'mode_game_will_stop'====== Args={}
Event: ======'mode_game_stopping'====== Args={}
Stopped.
Event: ======'modes_active_modes_changed'====== Args={}
Event: ======'mode_game_stopped'====== Args={}
Event: ======'clear'====== Args={'key': 'game'}
Shutdown because of an exception:
Runtime Exception
Traceback (most recent call last):
  File ".../mpf/core/machine.py", line 788, in _run_loop
    raise self._exception['exception']
  File "/usr/lib/python3.11/asyncio/tasks.py", line 415, in wait
    raise TypeError("Passing coroutines is forbidden, use tasks explicitly.")
TypeError: Passing coroutines is forbidden, use tasks explicitly.

```
The added conf was:

```
score_reels:
  sr_player1_10000:
    coil_inc: c_player1_reel10000
    switch_9: s_player1_reel10000
  sr_player1_1000:
    coil_inc: c_player1_reel1000
    switch_9: s_player1_reel1000
  sr_player1_100:
    coil_inc: c_player1_reel100
    switch_9: s_player1_reel100
  sr_player1_10:
    coil_inc: c_player1_reel10
    switch_9: s_player1_reel10

score_reel_groups:
  player1:
    reels: sr_player1_10000, sr_player1_1000, sr_player1_100, sr_player1_10, None
    tags: player1
    chimes: None, c_chime_1, c_chime_2, c_chime_3, None
    lights_tag: player1
```

This is with git version 0.57.0.dev25 running with Python 3.11.

I also tried with Python 3.10. It does not crash, but the "base" mode does not start. Actives modes just shows "game (20)" instead of "base (100)" and "game (20)". If I remove the "score_reel_groups" from conf, it works OK.

Should you need the full yaml config, I can attach it to the ticket.

Thanks
