### ISSUE TITLE
make config validator smarter

### ISSUE THREAD

**Issue by toomanybrians** [missionpinball/mpf#187]
It should catch errors like this:

```
slide_player:
  bug_bash_music_start: slide_77
  bug_splat_any: slide_78
  
  sound_player:
  bug bash mb music:
    start_events: bug_bash_music_start
    stop_events: bug_bash_music_stop
    sound: loop_This_is_halloween_finale
    loops: -1
    volume: 0.5 
```
