### ISSUE TITLE
Shot property persist_enable. when set false, still persists the enabled status

### ISSUE THREAD

**Issue by bosh** [missionpinball/mpf#1897]
I noticed this while building a shot that does not enable until after the first playfield_active, and realized I've actually seen this behavior before. I don't believe shot#persist_enable is working correctly when disabled.

Test failure showing this behavior is [here ](https://github.com/missionpinball/mpf/actions/runs/15480536954/job/43585439805?pr=1896#step:5:22)
PR [here](https://github.com/missionpinball/mpf/pull/1896)
Disabled case is [here](https://github.com/missionpinball/mpf/pull/1896/files#diff-26deb5bf1c7ccb964accc2f85936e14438482148179e81a72d38a3fa0220529aR14)

with a shot config that looks like:
```
shots:
  pe_test_property_disabled:
    profile: pe_profile
    switch: switch_29
    start_enabled: false
    persist_enable: false
    disable_events: pe_test_disable_all_shots
    enable_events: pe_test_enable_all_shots
```

Given start_enabled=false, persist=false, and a manually-defined enable event, there is no reason this shot should ever be enabled at mode start, or am I missing something?
