### ISSUE TITLE
Allow FAST driver & switch configs by board number

### ISSUE THREAD

**Issue by toomanybrians** [missionpinball/mpf#221]
Currently all FAST drivers and switches are cumulatively numbered starting with 00. Proposal is to allow an alternate number scheme where a dash in the number signifies board number, switch number (or driver number), like this:

```
switches:
  switch1:
    number: 0-0   # board 0, sw 0
  switch2:
    number: 2-5  # board 2, sw 5
```

same for drivers

Currently we do query each IO board at boot, and we know how many switches and drivers are on each and the order, so this would be fairly straightforward to implement
