### ISSUE TITLE
Shot with Show

### ISSUE THREAD

**Issue by jabdoa2** [missionpinball/mpf#543]
Usecase: Have a show one show step for every profile step.

Problem 1: Show in profile with start_step does not work:

```
shot_profiles:
  well_prepared:
    states:
      - name: off
        show: well_prepared
        start_step: 0
      - name: step1
        show: well_prepared
        start_step: 1
      - name: step2
        show: well_prepared
        start_step: 2
      - name: step3
        show: well_prepared
        start_step: 3
      - name: well_prepared
        show: well_prepared
        start_step: 4
```

Problem 2: With advancing show the show is not restored at the same step when the mode is stopped and started again:

```
shot_profiles:
  well_prepared:
    show: well_prepared
    states:
      - name: off
      - name: step1
      - name: step2
      - name: step3
      - name: well_prepared
```

show well_prepared.yaml:

```
#show_version=4
- duration: -1
  leds:
    (step1): off
    (step2): off
    (step3): off
    (well_prepared): off
- duration: -1
  leds:
    (step1): red
    (step2): off
    (step3): off
    (well_prepared): off
- duration: -1
  leds:
    (step1): red
    (step2): red
    (step3): off
    (well_prepared): off
- duration: -1
  leds:
    (step1): red
    (step2): red
    (step3): red
    (well_prepared): off
- duration: -1
  leds:
    (step1): red
    (step2): red
    (step3): red
    (well_prepared): white
```

shot:

```
shots:
  well_prepared_front:
    hit_events: ramp_equip_hits_front_complete
    profile: well_prepared
    show_tokens:
      step1: l_equip1_front
      step2: l_equip2_front
      step3: l_equip3_front
      well_prepared: l_well_prepared_front
```
