### ISSUE TITLE
Usecase: Show support for sequences

### ISSUE THREAD

**Issue by jabdoa2** [missionpinball/mpf#558]
Usecase: A mode where you need to hit multiple shots/ramps in a certain order.
1. Flash arrow before ramp 1
2. When user hits ramp 1, move to ramp 2
3. Flash arrow before ramp 2
   ...

Currently, you can implement this using a logicblock sequence + a show_player which is kind of complicated.

This works but I suppose we can make this simpler:

```
logic_blocks:
  sequences:
    one_on_one_front:
      events:
        - shot_orbit_left_front_hit
        - shot_equip_front_hit
        - shot_figur_front_hit
        - shot_troops_ramp_front_hit
        - shot_explosives_front_hit
        - shot_hidden_secret_front_hit
        - shot_orbit_right_front_hit
        - shot_upper_hole_front_hit
      enable_events: one_on_one_started
      events_when_complete: one_on_one_front_complete
      reset_on_complete: True
      disable_on_complete: False

show_player:
  one_on_one_started:
    flash_red:
      show_tokens:
        leds: l_orbit_left_arrow_front
      key: one_on_one_front
  logicblock_one_on_one_front_hit{step == 1}:
    flash_red:
      show_tokens:
        leds: l_equip_ramp_arrow_front
      key: one_on_one_front
  logicblock_one_on_one_front_hit{step == 2}:
    flash_red:
      show_tokens:
        leds: l_figur_arrow_front
      key: one_on_one_front
  logicblock_one_on_one_front_hit{step == 3}:
    flash_red:
      show_tokens:
        leds: l_troops_ramp_arrow_front
      key: one_on_one_front
  logicblock_one_on_one_front_hit{step == 4}:
    flash_red:
      show_tokens:
        leds: l_explosives_arrow_front
      key: one_on_one_front
  logicblock_one_on_one_front_hit{step == 5}:
    flash_red:
      show_tokens:
        leds: l_hidden_secret_arrow_front
      key: one_on_one_front
  logicblock_one_on_one_front_hit{step == 6}:
    flash_red:
      show_tokens:
        leds: l_orbit_right_arrow_front
      key: one_on_one_front
  logicblock_one_on_one_front_hit{step == 7}:
    flash_red:
      show_tokens:
        leds: l_upper_hole_arrow_front, l_orbit_left_arrow_front
      key: one_on_one_front
  logicblock_one_on_one_front_hit{step == 8}:
    one_on_one_front: stop
```

Another usecase might be: Same as above but with a timeout.
