### ISSUE TITLE
Trying to use same show for two sets of lights on same event crashes

### ISSUE THREAD

**Issue by GabeKnuth** [missionpinball/mpf#605]
(0.32)

Trying to indicate two shots with the same show using show_tokens in show_player, but apparently you can't do that.

Here's my show_player config:

```
show_player:
    mode_music_awards_started:
        ma_advertise_show:
            loops: -1
            show_tokens:
                led1: l_right_music_award
                led2: l_ramp_jackpot
                led3: l_south_america
        ma_advertise_show:
            loops: -1
            show_tokens:
                led1: l_advance_wizard
                led2: l_north_america
                led3: l_left_music_award
```

This causes a crash saying the same show was used twice in the config. That's true, but each one has different show tokens, so they are different.

Workaround for now is to just create two shows, but it seems like this is something that can happen often enough that we should address it.

**Comment by jabdoa2** [comment]
This should work in dev:

```
show_player:
    mode_music_awards_started.1:
        ma_advertise_show:
            loops: -1
            key: first
            show_tokens:
                led1: l_right_music_award
                led2: l_ramp_jackpot
                led3: l_south_america
    mode_music_awards_started.2:
        ma_advertise_show:
            loops: -1
            key: second
            show_tokens:
                led1: l_advance_wizard
                led2: l_north_america
                led3: l_left_music_award
```
