### ISSUE TITLE
add _overwrite: true to list-based configs

### ISSUE THREAD

**Issue by toomanybrians** [missionpinball/mpf#617]
example is to overwrite shows: entries, where each show is a list and not a dict. So to overwrite a show:

```
shows:
  flash:
    - _overwrite: true
    - duration: 250ms
      ...
```
