### ISSUE TITLE
Plugin config players require a standalone config section to work

### ISSUE THREAD

**Issue by toomanybrians** [missionpinball/mpf#759]
Example machine config:

```
#config_version=4

shows:
  my_show:
    - time: 0
      slides:
        my_slide:
        - type: text
          text: hello

show_player:
  mode_attract_started: my_show

#slide_player:
#  fake: dummy
```

Above config will not work. Uncomment the slide_player section and it's fine.

Has to do with how BCP transports are registered by looking for config sections in the file. Should probably just enumerate the plugins and register all of them.
