### ISSUE TITLE
Create a blinkenlights player

### ISSUE THREAD

**Issue by toomanybrians** [missionpinball/mpf#766]
For scenarios where you want lights to alternate between one (or more) colors, we should create a blinkenlights config player which can have all the specific properties, timing, and sync we'd want for that.

Details will need to be worked out. This is more of a placeholder for now.

**Comment by RoseAndres** [comment]
Hi there. As far as working out the details for this, who/what needs to be involved in working them out?

**Comment by jabdoa2** [comment]
Brian would be the right person but he is currently very busy in his private life (will probably be back in a few month). The idea here is to develop a feature to leverage RGB inserts on lane arrows inserts on modern machines. Let's say you got a blue, a red and green achievement in your game. Player completed blue and red. Now he should shoot for the scoop (or any shot) to collect the reward. Should the arrow be blue or red?

The idea here is to stack awards on the scoop by making it flash for 100ms in red and then 100ms in blue. Then 300ms off. Of couse this must stay in sync with all other inserts (even if those flash in only one or three colors). Sort order should be always the same. I'm not 100% sure if any machines actually do this currently.

Brian wanted to have it in MPF but we decided not to include this inside the light stack which only displays the show with the highest priority. Therefore this is a new feature which gathers all the colors for one light, creates (or parameters) a show and puts the show on the light (with sync_ms to keep it in sync with other shows).

Since it is nothing which is requests by any user you are free to make modifications/omit parts for now or create a minimal example. We always can extend it when people start using it.

**Comment by densminger** [comment]
I thought about some config options for how this might work a while back:

https://groups.google.com/g/mpf-users/c/tcU-dRa1zdQ/m/2dAS0_mABgAJ

**Comment by jabdoa2** [comment]
Let me just copy your suggestion over here:

> I considered something like what you suggested, but the thing with Game of Thrones is, there are 7 modes, any 2 of which can run concurrently.  So there would be 7 "slots" for the lights and that would mean the lights were in the "off" state most of the time.  I saw your link for the blinkenlights discussion and I think this would be a solution to this problem.  I started thinking about this some.  I was thinking to have a "blinkenlights" section of the config, along with a "blinkenlights_player".
> 
> Example:

```
blinkenlights:
  stark:
    each_duration: 1 # How long each color will be on per cycle
    off_duration: 1 # How long the light is off per cycle
    off_when_multiple: false # whether the light turns off in each cycle if multiple colors are defined for this blinkenlights already (ie, does it go red, green, off, red, green, off - or just red, green, red, green)
    light: l_stark_sigil # the light - this should be a color-changing light

blinkenlights_player:
  my_event:
    stark: # which blinkenlights to change
      action: add # add a color to the blinker
      key: mykey # each new color should have its own key so that it can be removed later
      color: white # the color of the blink

  mode_ended:
    stark:
      action: remove # remove the color from the blinker
      key: mykey # the key to remove
```

> So the blinkenlights section would define the blinker (lights and duration etc), and you would use the blinkenlights_player along with a key to add and remove a blink.

I like this. Very good starting point. I guess we do not even need the `mode_ended` as this would be auto-removed if the blinkenlight_player is used inside a mode.

Open questions to me:
- How long is each cycle? Does it get longer with more lights?
- How do we sync those cycles? For instance, one `blinkenlight` might have one colors on it and anther one two. Will one of them run faster? Will the off time be shorter?
- Is there a max for active lights per `blinkenlight`?
- How do we order lights? By mode priority? I guess it should be the same for all blinkenlights.

**Comment by densminger** [comment]
Here are my thoughts for the questions:

> How long is each cycle? Does it get longer with more lights?

Each cycle is determined by the ```each_duration``` parameter in the ```blinkenlights:``` section. So, if ```each_duration``` is 0.5, then every color that's added to the light will last for 0.5 seconds (plus 0.5 second for the "off" state of the light if ```off_when_multiple``` is set to ```true``` and there are more than 1 color).

> How do we sync those cycles? For instance, one ```blinkenlight``` might have one colors on it and anther one two. Will one of them run faster? Will the off time be shorter?

Multiple blinkenlights would not be sync'd together.  If one ```blinkenlight``` has 1 color, and other has 3 colors, then they would get out of sync.  But this is ok, since the idea is, they are signaling to the player which modes (colors) are active for that shot, so you wouldn't expect their cycles to be in sync.

> Is there a max for active lights per ```blinkenlight```?

I don't have a strong preference for this, but if it's necessary to implement a max, then I would guess once the max is reached, additional ```add``` to that ```blinkenlight``` would just be ignored.

> How do we order lights? By mode priority? I guess it should be the same for all blinkenlights.

My initial thought was to order this based on first-come-first-served.  I hadn't given this much thought to mode priority, since in Game of Thrones, all the relevant modes that use the ```blinkenlight``` would probably run at the same priority anyway.

**Comment by jabdoa2** [comment]
I think we should sync those somehow. Otherwise the result would look odd. Stern also somehow syncs and sorts them. Just did not figure out the logic yet.

**Comment by atummons** [comment]
I can add here for how Game of Thrones works with its lights.  There are two things to note that it does, and it is how I would propose it be introduced to MPF.

1) There is always a defined order, and that order cannot ever change.  That sequence always ends with an off segment (however, I think config to allow the user to say true or false would be good).  So if it is playing one light its on then off repeat.  If you have three (the max in GoT), it might go white, blue, light purple, off, then repeat.  So if you went into blinkenlight said an existing light is of this type, I would need to tell it the duration I want (which I would recommend the end user make the same for all of their blinkenlights), and if you have an off segment at the end of your loop.

2) There is never an issue with the sync_ms, as the all go for a fixed amount of time.  You cannot change the time to say red for 200ms and green for 100ms, and then off for 50ms.  It is always a fixed amount of time (We should let the user customize this).  But then all lights should blink for the same duration.  In GoT, if one light has color, another has two colors, and a third has three colors, they all hit the same period of time in any color or off.  So while they might be doing different things, the transition for colors is perfectly in sync always.  I have slow mo video of this if needed for reference.

So that being said, I would propose the code for the config should look like the following:

```
blinkenlights:
  stark:
    light: l_stark_sigil # the light - this should be a color-changing light
    off_when_multiple: false # whether the light turns off in each cycle if multiple colors are defined for this
          blinkenlights already (ie, does it go red, green, off, red, green, off - or just red, green, red, green)
    duration: 100ms #or whatever you want in ms
```

As for the player, I think that looks good.  Maybe it makes sense to have a priority for that color, which could be applied every time by the user when the player is called.  My thoughts here are that you could say I want white to be priority 100 so that it always plays first, and every time you're player queues a white light, you would need to put priority 100.  Then I want purple to be priority 0 so it always plays last.  I could then stack any colors that I want using the player and be able to give them relative priorities on their show.  This way you have full control over the order regardless of the order when the are invoked by the code.  And with duration being the same for all lights, they are in sync, although we probably still want sync_ms on the player, so that the flashes sync with all other lights going on the playfield.  Then whether this show, or another show would all be based on priority of the mode where its in, and relative priority of the show itself.  So this can still get covered up, just like any other show.

```
blinkenlights_player:
  my_event:
    stark: # which blinkenlights to change
      action: add # add a color to the blinker
      key: mykey # each new color should have its own key so that it can be removed later
      color: white # the color of the blink
      priority: 100
```
