### ISSUE TITLE
Conditional events in sound_player not registering in MPF or MC

### ISSUE THREAD

**Issue by GabeKnuth** [missionpinball/mpf#782]
Here's a snippet of config from BnD's base.yaml. MPF and MC log files attached. Neither is registering for these events.
[Archive.zip](https://github.com/missionpinball/mpf/files/784514/Archive.zip)

```
sound_player:
  drop_target_bank_drop_targets_mixed{down==1}:
    applause_1:
      action: play
      loops: 0
  drop_target_bank_drop_targets_mixed{down==2}:
    applause_2:
      action: play
      loops: 0
  drop_target_bank_drop_targets_mixed{down==3}:
    applause_3:
      action: play
      loops: 0
  drop_target_bank_drop_targets_mixed{down==4}:
    applause_4:
      action: play
      loops: 0
  drop_target_bank_drop_targets_down:
    applause_5:
      action: play
      loops: 0
```
