### ISSUE TITLE
multiball won't kick out new ball

### ISSUE THREAD

**Issue by GabeKnuth** [missionpinball/mpf#795]
@jabdoa2 I saw this tonight, but I need to go to bed and didn't want to waste a day before checking with you. Attached is a log, and towards the end of it I started a mode called jukebox_two_ball that starts a multiball after the main jukebox mode is completed. The mode starts, shows run, everything seems normal, but the game doesn't launch another ball. 

I believe the mode config is untouched since Expo (the "Multiball:" section looks right, anyway), and that this problem appeared around the time I switched to 0.33. I'm wondering if this doesn't have something to do with the ball controller stuff we saw a few weeks ago.

The log not verbose, but event_manager logging is set to full. I can turn verbose back on if you need it, but I was getting some serious lag while testing other things and turned it off. 
[jukebox multiball doesn't kick out new ball - MPF.log.zip](https://github.com/missionpinball/mpf/files/813021/jukebox.multiball.doesn.t.kick.out.new.ball.-.MPF.log.zip)

Mode config file is below:
```
#config_version=4
mode:
  priority: 600
  start_events: start_jukebox_two_ball
  stop_events: multiball_jukebox_two_ball_ended

event_player:
  mode_jukebox_two_ball_started:
    fade_out_base_music
  mode_jukebox_two_ball_stopping:
    fade_in_base_music

multiballs:
  jukebox_two_ball:
    ball_count: 2
    shoot_again: 5s
    start_events: mode_jukebox_two_ball_started

slide_player:
  mode_jukebox_two_ball_started:
    multiball:
      expire: 3s

slides:
  multiball:
    widgets:
      - type: text
        text: MULTIBALL
        expire: 2s
        style: dmd_huge
  ball_saved:
    widgets:
      - type: text
        text: BALL SAVED!
        expire: 2s
        style: dmd_huge

show_player:
  mode_jukebox_two_ball_started:
    jb_play_bnd_song:
      key: jb_active_video
    flash_jukebox:
      action: play


shows:
  jb_play_bnd_song:
    - duration: -1
      slides:
        jb_play_bnd_song:
          widgets:
          - type: video
            video: jb_hard_workin_man
            end_behavior: loop
            control_events:
              - event: stop_song
                action: stop
          target: stage
```
