### ISSUE TITLE
queue_relay_player causes TypeError: list indices must be integers, not QueuedEvent

### ISSUE THREAD

**Issue by GabeKnuth** [missionpinball/mpf#797]
Pretty sure this is a bug. I use the queue_relay_player to play a show when the balldevice_bd_lower_vuk_ball_eject_attempt event is posted. That event is a queue event, and when the queue_relay_player sees it, it fires off an event that plays a show, and the show fires off the wait_for event in the queue_relay_player. 

It works for the most part. There have been times when the show doesn't play (it's supposed to flash an LED a couple times), but I hadn't started troubleshooting it. This is the first time I've seen this crash, though.

Logs attached. 
[Archive 4.zip](https://github.com/missionpinball/mpf/files/816019/Archive.4.zip)

Relevant config below (It's all in the base mode in BnD):

```
queue_relay_player:
  balldevice_bd_lower_vuk_ball_eject_attempt:
    post: eject_flash
    wait_for: eject_alert_over

show_player:
  eject_flash:
    eject_alert:
      loops: 0
      show_tokens:
        led: l_lower_left_flasher
      priority: 1000000

shows:
  eject_alert:
    - time: 0
      leds:
        (led): on
    - time: 100ms
      leds:
        (led): off
    - time: 250ms
      leds:
        (led): on
    - time: 350ms
      leds:
        (led): off
    - time: 500ms
      leds:
        (led): on
    - time: 600ms
      leds:
        (led): off
    - time: 1300ms
      events: eject_alert_over
```
