### ISSUE TITLE
Mpf crashing on certain color values in my lightshow: RGB led hex values being treated as exponents

### ISSUE THREAD

**Issue by SwizzleFish** [missionpinball/mpf#803]
In creating lightshows, I have come across several color values that Mpf crashes on. 

It is my understanding this is due to mpf regarding the values as exponents, instead of strings. Is there a way that we can have Mpf regard these values as strings, as they seem to be legit hex color values.  Example:  274e97

Error in the log for the lightshow below:  ERROR : root : Invalid RGB string: 880000.0
Lightshow that crashes on several values: 

```
#show_version=4

# Frame Number: 0
- duration: 0.1
  leds:
    l_led4: 274e97
```
