### ISSUE TITLE
Validate LogicBlock Config Sections

### ISSUE THREAD

**Issue by jabdoa2** [missionpinball/mpf#828]
Currently this will silently do nothing:
```
logic_blocks:
    accrual:            # this has to be accruals to work
        rockblock:

            events:
              - northhit
              - easthit
              - southhit
              - westhit
            events_when_complete: rockyou_complete
            enable_events: mode_rockyou_started
            persist_state: true
            reset_on_complete: true
```

Raise an ConfigError in this case
