### ISSUE TITLE
Add global score multiplier

### ISSUE THREAD

**Issue by GabeKnuth** [missionpinball/mpf#833]
How difficult would it be to add in a global score multiplier that you could turn on/off with events? WOZ has this with their weak flippers mode (or lights out maybe? It's in there somewhere...), and I was hoping to use that same kind of thing in BnD without having to create a new scoring section with all of the scores doubled.

Something like:
```
scoring_multipliers:
  start_double_score:
    score: 2 # that's the multiplier
  stop_double_score:
    score: 1
```
Brian and I briefly chatted about this. Might be a fringe use case, but it seems like something people would use if it was there. 

Maybe this is mode specific, too, so if you put the scoring_multipliers section in your base mode, only base mode scores are affected. You'd have to put that section in other modes with the same events if you wanted those scores doubled, too. That would give a little bit of customization.
