### ISSUE TITLE
Text templates ng

### ISSUE THREAD

**Issue by jabdoa2** [missionpinball/mpf#959]
Current text templates look like this:

```
Player (player|number) Score: (player|score) Color: (machine|score)
```

Those work fine mostly. But they have a few limitations:
* No internationalization (i18n)
* No math/conditionals
* No formating
* Pipes are confusing because we use dots for other placeholders
* Not all placeholders are supported

Inline example (everything is converted to string):
```
Player {current_player.number}
```

Minimal example:
```
text: "Player {player_number:n}"
placeholders:
  - player_number:
        type: int
        value: current_player.number
```

Plural example (points is padded to 10 chars and centered):
```
text: "{points:^10d} point"
text_plural: "{points:^10d} points"
plural: current_player.score
placeholders:
  - points:
        type: int
        value: current_player.score
        default: 0 # in case there is no current player
```

Float formating example (fill with zero and max two decimals):
```
text: "{credits:0.2f} credits"
placeholders:
  - credits:
        type: int
        value: machine.credit_units
```

Multiple vars:
```
text: "Player {player_number:n} Score: {score:n} Color: {color}"
placeholders:
  - player_number:
        type: int
        value: current_player.number
  - score:
        type: float
        value: current_player.score
  - color:
        type: string
        value: "red" if current_player.score > 100 else: "blue"
```

All texts can be translated using gettext. We need to generate .po files and that is all. This also supports other plural forms which exist in some languages (e.g. for 21, 31, 41 and so on).

For number grouping {score:n} will work depending on the locale (e.g. in en_US or en_GB but not in de_DE). If you want to enfore it use {score:,} and it will happen in all locales.
