### ISSUE TITLE
Error while going through the tutorial

### ISSUE THREAD

**Issue by gabriellim** [missionpinball/mpf#979]
Hi!

I came across your project and would like to start contributing as a beginner. I am going through the tutorial at http://docs.missionpinball.org/en/latest/tutorial/3_get_flipping.html and I have ran into an error.

After adding the flipper devices, my config.yaml is shown below. I run ```mpf -b``` and get the following error ```mpf.exceptions.ConfigFileError.ConfigFileError: Config validation error: Entry flippers:left_flipper:playfield:playfield is not valid. 
Machine : ERROR: Failed to initialise MPF
root : MPF run loop ended.```

```
#config.yaml
#config_version=4

switches:
    s_left_flipper:
        number:
        tags: left_flipper
    s_right_flipper:
        number:
        tags: right_flipper

coils:
    c_flipper_left_main:
        number:
    c_flipper_left_hold:
        number:
        allow_enable: true
    c_flipper_right_main:
        number:
    c_flipper_right_hold:
        number:
        allow_enable: yes

flippers:
    left_flipper:
        main_coil: c_flipper_left_main
        hold_coil: c_flipper_left_hold
        activation_switch: s_left_flipper
    right_flipper:
        main_coil: c_flipper_right_main
        hold_coil: c_flipper_right_hold
        activation_switch: s_right_flipper
```

**Comment by jabdoa2** [comment]
Hi Gabriel, 

Welcome to MPF. The tutorial has not been updated for 0.50 unfortunately. However, i updated the config files for all steps in the examples repository: https://github.com/missionpinball/mpf-examples/tree/dev/tutorial/config. You need to define a playfield in dev:

```
playfields:
    playfield:
         tags: default
         default_source_device: bd_plunger  # use None in steps before 8
```

I will update the tutorial soon. Sorry for the inconvenience. 

Jan
